//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PROYECTOMVC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Reservas
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Reservas()
        {
            this.Pagos = new HashSet<Pagos>();
        }
    
        public int ID_reserva { get; set; }
        public int Cliente_ID { get; set; }
        public int Habitacion_ID { get; set; }
        public System.DateTime CheckIN { get; set; }
        public System.DateTime CheckOUT { get; set; }
        public Nullable<bool> Estatus { get; set; }
    
        public virtual Clientes Clientes { get; set; }
        public virtual Habitaciones Habitaciones { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Pagos> Pagos { get; set; }
    }
}
