//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PROYECTOMVC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Servicios_Habitacion
    {
        public int ID_ServHab { get; set; }
        public int Habitacion_ID { get; set; }
        public int Servicio_ID { get; set; }
        public int Empleado_ID { get; set; }
        public System.DateTime Fecha_Servicio { get; set; }
    
        public virtual Empleados Empleados { get; set; }
        public virtual Habitaciones Habitaciones { get; set; }
        public virtual Servicios Servicios { get; set; }
    }
}
